### ISSUE TITLE
Which keycaps are suitable for this version of dactyl?

### ISSUE THREAD

**Issue by ericktucto** [JPricey/dactyl-high-profile#2]
I have built your version, but I didn't know how to choose the keycaps, which keycaps did you use or which one do you suggest?

**Comment by JPricey** [comment]
Hi Eric, I used DSA profile caps for my build but others may work fine as well. I hope you enjoy yours!

**Comment by ericktucto** [comment]
Thank you very much, I'll be testing keys of that profile
